# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0035_resourcebase_dirty_state'),
        ('layers', '0033_auto_20180606_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WFPDocument',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.ResourceBase')),
                ('source', models.CharField(help_text='Please provide Source for the map - ex: WFP CO Afghanistan', max_length=255)),
                ('orientation', models.IntegerField(choices=[(0, b'Landscape'), (1, b'Portrait')], default=0, help_text='Orientation of the map', verbose_name=b'Orientation')),
                ('page_format', models.IntegerField(choices=[(4, b'A4'), (0, b'A0'), (1, b'A1'), (2, b'A2'), (3, b'A3')], default=0, help_text='Format of the map', verbose_name=b'Format')),
                ('doc_file', models.FileField(max_length=255, upload_to=b'documents', verbose_name='File')),
                ('extension', models.CharField(blank=True, max_length=128, null=True)),
                ('last_version', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Assign one or more categories to the map.', to='wfpdocs.Category', verbose_name=b'categories')),
                ('layers', models.ManyToManyField(blank=True, to='layers.Layer')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.resourcebase',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
