# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfpdocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wfpdocument',
            managers=[
            ],
        ),
    ]
