# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('people', '0028_auto_20180606_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=b'custom_thumbs')),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('gis_level', models.IntegerField(blank=True, choices=[(0, b'Basic'), (1, b'Intermediate'), (2, b'Advanced')], null=True)),
                ('duties_type', models.IntegerField(blank=True, choices=[(0, b'GIS'), (1, b'Not GIS')], null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfpid', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(max_length=254)),
                ('facility', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=254, null=True)),
                ('iso3', models.CharField(blank=True, max_length=254, null=True)),
                ('iso3_op', models.CharField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('locprecisi', models.CharField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('wfpregion', models.CharField(blank=True, max_length=254, null=True)),
                ('nat_staff', models.IntegerField(blank=True, null=True)),
                ('int_staff', models.IntegerField(blank=True, null=True)),
                ('lastcheckd', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('createdate', models.DateField(blank=True, null=True)),
                ('updatedate', models.DateField(blank=True, null=True)),
                ('objectidol', models.FloatField(blank=True, null=True)),
                ('precisiono', models.CharField(blank=True, max_length=254, null=True)),
                ('verifiedol', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['place'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfpgis.Office'),
        ),
    ]
