# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 08:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfpgis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(55.17 25.14)', srid=4326),
            preserve_default=False,
        ),
    ]
